apiVersion: v1
kind: Service
metadata:
  name: production-app-service
  namespace: default
spec:
  selector:
    app: production-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

